# Site settings
title: Kolektif Mavi
email: mavidurak.io@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mavidurak-IO Sakarya'da yaşayan ya da Sakarya'da öğrenim 
  gören geliştiricilerin oluşturduğu topluluktur.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mavidurak.github.io" # the base hostname & protocol for your site
twitter_username: mavidurakio
github_username:  mavidurak
paginate: 7

# Build settings
markdown: kramdown

