# Site settings
title: Kolektif Mavi
email: mavidurak.io@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mavidurak-IO Sakarya'da yaşayan ya da Sakarya'da öğrenim 
  gören geliştiricilerin oluşturduğu topluluktur.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mavidurak.github.io" # the base hostname & protocol for your site
twitter_username: mavidurakio
github_username:  mavidurak
paginate: 7

# Build settings
markdown: kramdown


authors:
  ozziest:
    display_name: Özgür Adem Işıklı
    bio: Ahir Ar-Ge AŞ bünyesinde Web Developer olarak çalışıyor.
    avatar: https://pbs.twimg.com/profile_images/466225886530789377/P-fkjNMZ.jpeg
    email: i.ozguradem@gmail.com
    web: http://ozziest.github.io
    twitter: iozguradem
    github: ozziest
    facebook: TheMornie
    linkedin: http://tr.linkedin.com/in/ozguradem/
  frknbasaran:
    display_name: Furkan Başaran
    bio: Toyota Motor Europe bünyesinde Web Developer olarak çalışıyor.
    avatar: https://avatars0.githubusercontent.com/u/6316032?v=2&s=96
    email: frknbasaran@gmail.com
    web: furkanbasaran.com
    twitter: frknbasaran
    github: frknbasaran
    facebook: frknbasaran
    linkedin: http://tr.linkedin.com/pub/furkan-ba%C5%9Faran/73/731/b3b/

